# Generated by Django 4.0.6 on 2022-08-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quistion_text',
            new_name='question_text',
        ),
    ]
